import { Button, ButtonProps } from '@src/components'
import {
  Selection,
  SelectionZone,
  useSelectionZone,
} from '@src/components/SelectionZone'
import { COLUMNS } from '@src/store'
import { Box, Text } from 'ink'
import React from 'react'

export const Security: React.FC = () => {
  const parentZone = useSelectionZone()!

  return (
    <SelectionZone
      prevKey="upArrow"
      nextKey="downArrow"
      isActive={parentZone.selection === COLUMNS.MAIN}
    >
      <Box flexDirection="column">
        <Box marginTop={-1}>
          <Text> Security </Text>
        </Box>
        <Text>The security settings of your wallet</Text>

        <Box marginTop={1} flexDirection="column">
          <Text bold>Password</Text>
          <Text>Change your wallet login password</Text>
          <Selection<ButtonProps> activeProps={{ isFocused: true }}>
            <Button alignSelf="center" width="50%" onPress={() => null}>
              Update password
            </Button>
          </Selection>
        </Box>

        <Box marginTop={1} flexDirection="column">
          <Text bold>Recovery Phrases</Text>
          <Text>
            A recovery phrase grants full access to all accounts generated by
            it. You can manage and export your recovery phrases.
          </Text>
          <Selection<ButtonProps> activeProps={{ isFocused: true }}>
            <Button alignSelf="center" width="50%" onPress={() => null}>
              Show the Phrases
            </Button>
          </Selection>
        </Box>

        <Box marginTop={1} flexDirection="column">
          <Text bold>Private Key</Text>
          <Text>
            The private key grants full access to the current account. You can
            export the account by exporting its private key.
          </Text>
          <Selection<ButtonProps> activeProps={{ isFocused: true }}>
            <Button alignSelf="center" width="50%" onPress={() => null}>
              Show the Private key
            </Button>
          </Selection>
        </Box>
      </Box>
    </SelectionZone>
  )
}
